//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace termins
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class termsEntities2 : DbContext
    {
        public static termsEntities2 _context;
        public termsEntities2()
            : base("name=termsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static termsEntities2 GetContext()
        {
            if (_context == null)
                _context = new termsEntities2();
            return _context;
        }

        public virtual DbSet<century> centuries { get; set; }
        public virtual DbSet<era> eras { get; set; }
        public virtual DbSet<science> sciences { get; set; }
        public virtual DbSet<sec> secs { get; set; }
        public virtual DbSet<source> sources { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<term> terms { get; set; }
    }
}
